### ISSUE TITLE
Make nullable types show as nullable in embed

### ISSUE THREAD

**Issue by tipakA** [TeeSeal/discord.js-docs#2]
At the moment, Properties that can return `null` doesn't show up in `?type` format.
Good example could be GuildMember.nickname. Type is just `string`, while at docs it's `?string`

**Comment by TeeSeal** [comment]
Handled in https://github.com/TeeSeal/discord.js-docs/commit/ed7ae53d60a674efa105b4f21e8a5de55111c90a. Thanks for the report.
