### ISSUE TITLE
Make url valid

### ISSUE THREAD

**Issue by Kayxue** [TeeSeal/discord.js-docs#22]
Can you make the urls valid please? 🥺🥺🥺
![image](https://user-images.githubusercontent.com/26020165/161386735-d47a60e6-bb4c-48d1-add0-df659f05aa96.png)

**Comment by TeeSeal** [comment]
@Kayxue should be fixed in 0.2.5

Update your package and test it out!

**Comment by Kayxue** [comment]
It fixed! Thanks!
